<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>dev.molaya.tests</groupId>
    <artifactId>backprods</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>Dev Products Tech Solution</name>
    <description>Backend dev test solution by molaya</description>
    <developers>
        <developer>
            <id>molaya</id>
            <name>Marlon Olaya</name>
            <email>me@molaya.dev</email>
        </developer>
    </developers>
    <packaging>pom</packaging>
    <properties>
        <java.version>21</java.version>

        <jacoco.version>0.8.13</jacoco.version>
        <jacoco-maven-plugin.minimum>0.8</jacoco-maven-plugin.minimum>
        <jacoco-maven-plugin.excludes>**/dto/**,**/model/**,**/exception/**</jacoco-maven-plugin.excludes>

        <spotless.version>2.46.1</spotless.version>
        <palantir-java-format.version>2.71.0</palantir-java-format.version>

        <openapi-generator-maven-plugin.version>7.17.0</openapi-generator-maven-plugin.version>
        <jackson-databind-nullable.version>0.2.8</jackson-databind-nullable.version>
        <jakarta.validation-api.version>3.1.1</jakarta.validation-api.version>
        <swagger-annotations.version>2.2.41</swagger-annotations.version>
        <jackson-datatype-jsr310.version>2.20.1</jackson-datatype-jsr310.version>

        <mapstruct.version>1.6.3</mapstruct.version>
        <lombok.mapstruct.binding.version>0.2.0</lombok.mapstruct.binding.version>
        <lombok.version>1.18.38</lombok.version>
    </properties>

    <modules>
        <module>domain</module>
        <module>application</module>
        <module>adapters</module>
        <module>bootstrap</module>
    </modules>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dev.molaya.tests</groupId>
                <artifactId>domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.molaya.tests</groupId>
                <artifactId>application</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.molaya.tests</groupId>
                <artifactId>adapters</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <optional>true</optional>
            </dependency>
            <!-- MapStruct -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-mapstruct-binding</artifactId>
                <version>${lombok.mapstruct.binding.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>${jackson-datatype-jsr310.version}</version>
            </dependency>
            <!-- Usually will be in custom parent pom, but for simplicity included here -->
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>${swagger-annotations.version}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.validation</groupId>
                <artifactId>jakarta.validation-api</artifactId>
                <version>${jakarta.validation-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openapitools</groupId>
                <artifactId>jackson-databind-nullable</artifactId>
                <version>${jackson-databind-nullable.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <!-- Jacoco Coverage -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <append>true</append>
                    <excludes>
                        ${jacoco-maven-plugin.excludes},
                        **/dto/**,
                        **/config/**,
                        **/exceptions/**
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>agent-for-ut</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>agent-for-it</id>
                        <goals>
                            <goal>prepare-agent-integration</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jacoco-site</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jacoco-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <excludes>${jacoco-maven-plugin.excludes}</excludes>
                            <rules>
                                <rule>
                                    <element>BUNDLE</element>
                                    <limits>
                                        <limit>
                                            <counter>INSTRUCTION</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>${jacoco-maven-plugin.minimum}</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Spotless plugin for code formatting -->
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless.version}</version>

                <dependencies>
                    <!-- Spotless dependencies using palantir -->
                    <dependency>
                        <groupId>com.palantir.javaformat</groupId>
                        <artifactId>palantir-java-format</artifactId>
                        <version>${palantir-java-format.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <formats>
                        <format>
                            <includes>
                                <include>src/**/resources/**/*.xml</include>
                                <include>src/**/resources/**/*.xsd</include>
                            </includes>
                            <trimTrailingWhitespace/>
                            <indent>
                                <tabs>true</tabs>
                                <spacesPerTab>4</spacesPerTab>
                            </indent>
                        </format>
                    </formats>
                    <!-- define a language-specific format -->
                    <pom>
                        <includes>
                            <include>pom.xml</include>
                        </includes>
                    </pom>
                    <java>
                        <palantirJavaFormat>
                            <version>${palantir-java-format.version}</version>                     <!-- optional -->
                            <style>PALANTIR</style>                       <!-- or AOSP/GOOGLE (optional) -->
                        </palantirJavaFormat>
                        <importOrder/> <!-- standard import order -->
                        <formatAnnotations/>
                    </java>
                    <yaml>
                        <includes>
                            <include>src/**/*.yaml</include>
                        </includes>
                        <prettier/>
                    </yaml>
                    <gherkin>
                        <includes>
                            <include>src/**/*.feature</include>
                        </includes>
                        <gherkinUtils/>
                    </gherkin>
                    <markdown>
                        <includes>
                            <include>**/*.md</include>
                        </includes>
                        <flexmark/>
                    </markdown>
                </configuration>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                    <configuration>
                        <useFile>false</useFile>
                        <includes>**/*Test.java</includes>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <parameters>true</parameters>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <debug>true</debug>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                            <dependency>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok-mapstruct-binding</artifactId>
                                <version>${lombok.mapstruct.binding.version}</version>
                            </dependency>
                        </annotationProcessorPaths>
                        <compilerArgs>
                            <compilerArg>
                                -Amapstruct.defaultComponentModel=spring
                            </compilerArg>
                        </compilerArgs>
                    </configuration>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>


</project>
