openapi: 3.0.0
info:
  title: SimilarProducts
  version: '1.0'
servers:
  - url: 'http://localhost:5000'
paths:
  '/product/{productId}/similar':
    parameters:
      - schema:
          type: string
        name: productId
        in: path
        required: true
    get:
      operationId: get-product-similar
      summary: Similar products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: 'List of similar products to a given one ordered by similarity'
                minItems: 0
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - name
                    - price
                    - availability
                  properties:
                    id:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                    price:
                      type: number
                    availability:
                      type: boolean