server:
  port: 5000

spring:
  threads:
    virtual:
      enabled: true

similar-products:
  max-concurrent-calls: 10

external:
  product-service:
    base-url: http://host.docker.internal:3001

resilience4j:
  retry:
    instances:
      productService:
        max-attempts: 4
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException.InternalServerError
          - org.springframework.web.client.HttpServerErrorException.BadGateway
          - org.springframework.web.client.HttpServerErrorException.ServiceUnavailable
          - org.springframework.web.client.HttpServerErrorException.GatewayTimeout
  circuitbreaker:
    instances:
      productService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException.BadRequest
          - org.springframework.web.client.HttpClientErrorException.NotFound
  bulkhead:
    instances:
      productService:
        maxConcurrentCalls: 20
        maxWaitDuration: 200ms

