server:
  port: 5000

endpoints:
  existingApi:
    url: ${endpoints.existingApi.givenUrl:${endpoints.existingApi.formedUrl}}
    formedUrl: ${endpoints.existingApi.basePath}:${endpoints.existingApi.port}
    givenUrl: http://localhost:3001
    basePath: http://localhost
    port: 3001