<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.molaya.tests</groupId>
        <artifactId>backprods</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>adapters</artifactId>
    <name>Adapters Module</name>

    <properties>
        <openapi.out.client>dev.molaya.tests.adapters.out.client</openapi.out.client>
        <openapi.in.rest>dev.molaya.tests.adapters.in.rest</openapi.in.rest>
        <springdoc-openapi-starter-webmvc-ui.version>2.8.6</springdoc-openapi-starter-webmvc-ui.version>
        <openapi-generator-maven-plugin.apiNameSuffix>GenApi</openapi-generator-maven-plugin.apiNameSuffix>
        <jacoco-maven-plugin.excludes>**/*${openapi-generator-maven-plugin.apiNameSuffix}.java</jacoco-maven-plugin.excludes>
    </properties>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>application</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc-openapi-starter-webmvc-ui.version}</version>
        </dependency>
        <!-- open api -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator-maven-plugin.version}</version>
                <executions>
                    <!-- open api client -->
                    <execution>
                        <id>client-interface-generator</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/existingApis.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>webclient</library>
                            <apiPackage>${openapi.out.client}</apiPackage>
                            <modelPackage>${openapi.out.client}.dto</modelPackage>
                            <apiNameSuffix>${openapi-generator-maven-plugin.apiNameSuffix}</apiNameSuffix>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <useJakartaEe>true</useJakartaEe>
                                <reactive>true</reactive>
                            </configOptions>
                        </configuration>
                    </execution>
                    <!-- end open api client -->
                    <!-- open api rest -->
                    <execution>
                        <id>rest-interface-generator</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/similarProducts.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>${openapi.in.rest}</apiPackage>
                            <modelPackage>${openapi.in.rest}.dto</modelPackage>
                            <generateApiTests>false</generateApiTests>
                            <apiNameSuffix>${openapi-generator-maven-plugin.apiNameSuffix}</apiNameSuffix>
                            <configOptions>
                                <reactive>true</reactive>
                                <interfaceOnly>true</interfaceOnly>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <useJakartaEe>true</useJakartaEe>
                                <restControllerStyle>true</restControllerStyle>
                            </configOptions>
                        </configuration>
                    </execution>
                    <!-- end open api rest -->
                </executions>
            </plugin>
        </plugins>
    </build>
    
</project>