spring.application.name=products
server.port=5000

integrations.product-client.base-url=http://localhost:3001/product

# OpenAPI configuration
springdoc.api-docs.enabled=true

# Redis configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=6379