spring.application.name=products
server.port=${SERVER_PORT:5000}

integrations.productClient.baseUrl=http://${EXTERNAL_API_HOST:localhost:3001}/product
integrations.productClient.readTimeout=3000
integrations.productClient.connectTimeout=2000

# OpenAPI configuration
springdoc.api-docs.enabled=true

# Cache configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
cache.ttl.millis=30000
cache.similarProducts.name=similarProducts

# Circuit Breaker
resilience4j.circuitbreaker.instances.productClient.sliding-window-size=10
resilience4j.circuitbreaker.instances.productClient.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.productClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productClient.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.productClient.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.productClient.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.productClient.register-health-indicator=true
resilience4j.circuitbreaker.instances.productClient.ignore-exceptions=org.challenge.products.domain.exception.ProductNotFoundException

# Actuator
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true