spring.application.name=msdavidmobilephone
server.port=5000

# External API
external.api.base-url=http://localhost:3001

# Timeouts
spring.mvc.async.request-timeout=5000
server.tomcat.connection-timeout=5000

# Feign Client
feign.client.config.default.connect-timeout=3000
feign.client.config.default.read-timeout=3000
