spring.application.name=similarproducts
server.port=5000

# Set desired logging level, we adjust INFO to avoid too much logs due to performance requirements
logging.level.com.sngular.similarproducts=INFO

app.product-service.base-url=http://localhost:3001