spring.application.name=similar-products

# === Server ===
server.port=5000

# === External API ===
external.api.base-url=http://localhost:3001

spring.cache.type=caffeine

# Cache eviction interval in milliseconds (e.g., 1 minute)
cache.product-detail.ttl=60000